# -*- encoding: utf-8 -*-
$:.push File.expand_path('../lib', __FILE__)
require 'calabash-cucumber/version'

# ruby files
ruby_files = Dir.glob('lib/**/*.rb') + Dir.glob('bin/**/*.rb')

# additional files in bin
additional_bin_files = %w(bin/cal.xcconfig bin/CalabashSetup bin/calabash-ios)

# bin help file
bin_help = %w(doc/calabash-ios-help.txt)

# the calabash framework
staticlib = %w(staticlib/calabash.framework.zip)

# calabash dylibs
dylibs = %w(dylibs/libCalabashARM.dylib dylibs/libCalabashSim.dylib)

# files in script
scripts = %w(scripts/.irbrc)

# files in script/data
scripts_data = Dir.glob('scripts/data/*.plist')

# pre-defined Steps
features = Dir.glob('features/**/*.rb')

# resources for the skeleton project generated by calabash-ios gen
features_skeleton = Dir.glob('features-skeleton/**/*.*')

license = %w(LICENSE)

gem_files = ruby_files + additional_bin_files + bin_help + staticlib + scripts + scripts_data + features + features_skeleton + license + dylibs

Gem::Specification.new do |s|
  s.name        = 'calabash-cucumber'
  s.version     = Calabash::Cucumber::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['Karl Krukow']
  s.email       = ['karl@lesspainful.com']
  s.homepage    = 'http://calaba.sh'
  s.summary     = %q{Client for calabash-ios-server for automated functional testing on iOS}
  s.description = %q{calabash-cucumber drives tests for native iOS apps. You must link your app with calabash-ios-server framework to execute tests.}
  s.files         = gem_files
  s.test_files    = []
  s.executables   = %w(calabash-ios)
  s.require_paths = %w(lib)
  s.license       = 'EPL-1.0'

  s.required_ruby_version = '>= 2.0'

  s.add_dependency('cucumber')
  # Avoid 1.0.5 release; has an errant 'binding.pry'.
  s.add_dependency('edn')
  s.add_dependency('slowhandcuke')
  s.add_dependency('geocoder')
  s.add_dependency('httpclient')
  s.add_dependency("clipboard")
  s.add_dependency("run_loop", ">= 4.2", "< 5.0")

  # Shared with run-loop.
  s.add_dependency('json')
  s.add_dependency('awesome_print')

  s.add_development_dependency 'yard'
  s.add_development_dependency 'redcarpet'

  # Shared with run-loop.
  s.add_development_dependency("rspec_junit_formatter")
  s.add_development_dependency 'luffa' # Remove ASAP.
  s.add_development_dependency 'rake'
  s.add_development_dependency 'rspec'
  s.add_development_dependency 'pry'
  s.add_development_dependency 'pry-nav'
  s.add_development_dependency "rb-readline"
  s.add_development_dependency 'guard-rspec'
  s.add_development_dependency 'guard-bundler'
  # Pin to 3.0.6; >= 3.1.0 requires ruby 2.2. This is guard dependency.
  s.add_development_dependency("listen")
  s.add_development_dependency 'growl'
  s.add_development_dependency 'stub_env'
  # Sometimes JSON.parse is failing to parse JSON dumped to a file.
  s.add_development_dependency("oj")
end
