require 'bundler'
require 'fileutils'

Bundler::GemHelper.install_tasks


task :build_server do

  FRAMEWORK='calabash.framework'
  ZIP_FILE="#{FRAMEWORK}.zip"

  def build_server
    return if ENV['SKIP_SERVER']
    framework_path = ENV['FRAMEWORK_PATH']

    unless framework_path
      dir = ENV['CALABASH_SERVER_PATH'] || File.join('..', '..', 'calabash-ios-server')
      unless File.exist?(dir)
        raise <<EOF
        Unable to find calabash server checked out at #{dir}.
        Please checkout as #{dir} or set CALABASH_SERVER_PATH to point
        to Calabash server (branch 0.9.x).
EOF
      end

      FileUtils.cd(dir) do
        puts 'Building Server'
        cmd = 'xcodebuild build -project calabash.xcodeproj -target Framework -configuration Debug -sdk iphonesimulator6.1'
        puts cmd
        puts `#{cmd}`

        unless File.exist?(FRAMEWORK)
          raise 'Unable to build framework'
        end
        framework_path = File.expand_path(FRAMEWORK)
      end
    end

    puts "Zipping down framework #{framework_path}"

    FileUtils.mkdir_p('staticlib')
    output_path = File.join('staticlib', ZIP_FILE)

    zip_cmd = "zip -q -r #{output_path} #{framework_path}"
    puts zip_cmd
    puts `#{zip_cmd}`

    unless File.exist?(output_path)
      raise 'Unable to zip down framework...'
    end

    puts "Server built to path #{output_path}"

  end

  build_server

end

task :build => [:build_server]
task :install => [:build_server]
task :release => [:build_server]

