#!/usr/bin/env bash

CUCUMBER_ARGS=$*

cd calabash-cucumber

RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to change directory to calabash-cucumber - should called as 'script/ci'"
    exit $RETVAL
else
    echo "INFO: changed directory to ${PWD}"
fi

../script/shared-bundler-tasks.sh

# on-simulator tests of features in test/cucumber
cd test/cucumber
rm -rf Gemfile
rm -rf Gemfile.lock
rm -rf .bundle
rm -rf vendor
bundle install --deployment

# remove any stale targets
bundle exec calabash-ios sim reset

# Disable exiting on error so script continues if tests fail
set +o errexit

export APP_BUNDLE_PATH="./LPSimpleExample-cal.app"

RETVAL=0

NL=$'\n'
SIMS_PASSING="PASSING SIMS${NL}"
SIMS_FAILING="FAILING SIMS${NL}"

SIM_PROFILE=sim61_4in
SIM='iPhone Retina (4-inch) - Simulator - iOS 6.1'
MSG="$SIM_PROFILE => $SIM${NL}"
bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
PASS_FAIL=$?
if [ $PASS_FAIL = 0 ]; then
    SIMS_PASSING="${SIMS_PASSING}${MSG}"
else
    SIMS_FAILING="${SIMS_FAILING}${MSG}"
fi
RETVAL=$(($RETVAL+$PASS_FAIL))

SIM_PROFILE=sim71_4in
SIM='iPhone Retina (4-inch) - Simulator - iOS 7.1'
bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
PASS_FAIL=$?
MSG="$SIM_PROFILE => $SIM${NL}"
if [ $PASS_FAIL = 0 ]; then
    SIMS_PASSING="${SIMS_PASSING}${MSG}"
else
    SIMS_FAILING="${SIMS_FAILING}${MSG}"
fi
RETVAL=$(($RETVAL+$PASS_FAIL))

# iOS 7.1 64 bit flickers on travis ci because the
# host VM sometimes pops a security dialog.
# Instead we run on the 7.0 64 bit simulator.
if [ -z $TRAVIS ]; then
    SIM_PROFILE=sim71_64b
    SIM='iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
    MSG="$SIM_PROFILE => $SIM${NL}"
    bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
    PASS_FAIL=$?
    if [ $PASS_FAIL = 0 ]; then
        SIMS_PASSING="${SIMS_PASSING}${MSG}"
    else
        SIMS_FAILING="${SIMS_FAILING}${MSG}"
    fi
    RETVAL=$(($RETVAL+$PASS_FAIL))
else
    SIM_PROFILE=sim70_64b
    SIM='iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.0'
    MSG="$SIM_PROFILE => $SIM${NL}"
    bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
    PASS_FAIL=$?
    if [ $PASS_FAIL = 0 ]; then
        SIMS_PASSING="${SIMS_PASSING}${MSG}"
    else
        SIMS_FAILING="${SIMS_FAILING}${MSG}"
    fi
    RETVAL=$(($RETVAL+$PASS_FAIL))
fi

SIM_PROFILE=sim61r
SIM='iPhone Retina (3.5-inch) - Simulator - iOS 6.1'
MSG="$SIM_PROFILE => $SIM${NL}"
bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
PASS_FAIL=$?
if [ $PASS_FAIL = 0 ]; then
    SIMS_PASSING="${SIMS_PASSING}${MSG}"
else
    SIMS_FAILING="${SIMS_FAILING}${MSG}"
fi
RETVAL=$(($RETVAL+$PASS_FAIL))

SIM_PROFILE=sim71r
SIM='iPhone Retina (3.5-inch) - Simulator - iOS 6.1'
MSG="$SIM_PROFILE => $SIM${NL}"
bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
PASS_FAIL=$?
if [ $PASS_FAIL = 0 ]; then
    SIMS_PASSING="${SIMS_PASSING}${MSG}"
else
    SIMS_FAILING="${SIMS_FAILING}${MSG}"
fi
RETVAL=$(($RETVAL+$PASS_FAIL))

SIM_PROFILE=sim61_ipad_r
SIM='iPad Retina - Simulator - iOS 6.1'
MSG="$SIM_PROFILE => $SIM${NL}"
bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
PASS_FAIL=$?
if [ $PASS_FAIL = 0 ]; then
    SIMS_PASSING="${SIMS_PASSING}${MSG}"
else
    SIMS_FAILING="${SIMS_FAILING}${MSG}"
fi
RETVAL=$(($RETVAL+$PASS_FAIL))

SIM_PROFILE=sim71_ipad_r
SIM='iPad Retina - Simulator - iOS 7.1'
MSG="$SIM_PROFILE => $SIM${NL}"
bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
PASS_FAIL=$?
if [ $PASS_FAIL = 0 ]; then
    SIMS_PASSING="${SIMS_PASSING}${MSG}"
else
    SIMS_FAILING="${SIMS_FAILING}${MSG}"
fi
RETVAL=$(($RETVAL+$PASS_FAIL))

# iOS 7.1 64 bit flickers on travis ci because the
# host VM sometimes pops a security dialog.
# Instead we run on the 7.0 64 bit simulator.
if [ -z $TRAVIS ]; then
    SIM_PROFILE=sim71_ipad_r_64b
    SIM='iPad Retina (64-bit) - Simulator - iOS 7.1'
    MSG="$SIM_PROFILE => $SIM${NL}"
    bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
    PASS_FAIL=$?
    if [ $PASS_FAIL = 0 ]; then
        SIMS_PASSING="${SIMS_PASSING}${MSG}"
    else
        SIMS_FAILING="${SIMS_FAILING}${MSG}"
    fi
    RETVAL=$(($RETVAL+$PASS_FAIL))
else
    SIM_PROFILE=sim70_ipad_r_64b
    SIM='iPad Retina (64-bit) - Simulator - iOS 7.0'
    MSG="$SIM_PROFILE => $SIM${NL}"
    bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
    PASS_FAIL=$?
    if [ $PASS_FAIL = 0 ]; then
        SIMS_PASSING="${SIMS_PASSING}${MSG}"
    else
        SIMS_FAILING="${SIMS_FAILING}${MSG}"
    fi
    RETVAL=$(($RETVAL+$PASS_FAIL))
fi

SIM_PROFILE=sim61_sl
SIM='iPhone (3.5-inch) - Simulator - iOS 6.1 (launched with ios-sim)'
MSG="$SIM_PROFILE => $SIM${NL}"
bundle exec cucumber -p $SIM_PROFILE $CUCUMBER_ARGS
PASS_FAIL=$?
if [ $PASS_FAIL = 0 ]; then
    SIMS_PASSING="${SIMS_PASSING}${MSG}"
else
    SIMS_FAILING="${SIMS_FAILING}${MSG}"
fi
RETVAL=$(($RETVAL+$PASS_FAIL))

set -o errexit

echo "=== SUMMARY ==="
echo $"${SIMS_PASSING}"
echo ""
echo $"${SIMS_FAILING}"
echo ""

if [ $RETVAL != 0 ]; then
    echo "FAIL: failed $RETVAL out of 9 simulators"
    exit $RETVAL
fi

exit $RETVAL
