source "https://rubygems.org"

gem "calabash-cucumber", :path => "../../"
gem "run_loop", :github => "calabash/run_loop", :branch => "develop"
gem "cucumber", "~> 2.0"
gem "rspec", "~> 3.0"
gem "pry"
gem "pry-nav"

