source 'https://rubygems.org'

if ENV['TRAVIS'] || ENV['JENKINS_HOME']
  gem 'run_loop', :path => '../../../run_loop'
end

gem 'calabash-cucumber', :path => '../../../'

gem 'retriable', '~> 2.0'
gem 'bundler', '~> 1.6'
gem 'rspec', '~> 3.0'
gem 'pry'
gem 'pry-nav'
gem 'luffa'

